# Generated by Django 4.1.3 on 2022-11-02 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_created=True)),
                ('title', models.CharField(max_length=120)),
                ('link', models.URLField()),
                ('price', models.IntegerField()),
            ],
        ),
    ]
